# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 836fdeec6ce802208fa092f57f9f191d8631ae82f7a53ab15f84c83f4511afae6e16831e428ca1776d7972fc616cb57773753f8de16f270fe5e17214ec11530c

test:
  secret_key_base: 23a16f9b57a43a3a71345f34a9e22138a3572eedc0fb17fea8b02fc9b758f176d92608f8b1cc1f3e8bb0ba6195f1119aa413bb988543940afe27cb6d482bc164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
